language: cpp
sudo: required
dist: trusty
compiler:
- clang
before_script: ./autogen.sh
os:
- linux
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
